/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorWorkArea;

import business.employee.Employee;
import business.enterprise.Enterprise;
import business.organization.AssistantOrganization;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import business.role.Role;
import business.useraccount.UserAccount;
import business.workqueue.LabTestWorkRequest;
import business.workqueue.PatientResultRequest;
import business.workqueue.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zack
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    DoctorOrganization organization;
    Enterprise enterprise;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        populateTestTable();
        populatePatientTable();
    }

    public void populateTestTable(){
        DefaultTableModel model = (DefaultTableModel) testJTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request : account.getWorkQueue().getWorkRequestCatalog()){
            Object[] row = new Object[6];
            row[0] = format.format(request.getRequestDate());
            if(request.getResolveDate() == null){
                row[1] = null;
            }
            else{
                row[1] = format.format(request.getResolveDate());
            }
            row[2] = request;
            row[3] = request.getReceiver();
            row[4] = request.getStatus();
            String result = ((LabTestWorkRequest) request).getTestResult();
            row[5] = result == null ? "Waiting" : result;
            model.addRow(row);
        }
    }
    
    public void populatePatientTable(){
        DefaultTableModel model = (DefaultTableModel) patientJTable.getModel();
        model.setRowCount(0);
        for(WorkRequest workRequest : organization.getWorkQueue().getWorkRequestCatalog()){
                Object[] row = new Object[2];
                row[0] = workRequest.getSender().getEmployee().getName();
                row[1] = format.format(workRequest.getRequestDate());
                model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        testJTable = new javax.swing.JTable();
        requestJButton = new javax.swing.JButton();
        messageJLabel = new javax.swing.JLabel();
        testMessageJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientJTable = new javax.swing.JTable();
        messageJLabel1 = new javax.swing.JLabel();
        patientMessageJTextField = new javax.swing.JTextField();
        sendResultJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Resolve Date", "Message", "Receiver", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(testJTable);
        if (testJTable.getColumnModel().getColumnCount() > 0) {
            testJTable.getColumnModel().getColumn(0).setResizable(false);
            testJTable.getColumnModel().getColumn(1).setResizable(false);
            testJTable.getColumnModel().getColumn(2).setResizable(false);
            testJTable.getColumnModel().getColumn(3).setResizable(false);
            testJTable.getColumnModel().getColumn(4).setResizable(false);
            testJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 1101, 269));

        requestJButton.setText("Request Test");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });
        add(requestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 344, -1, -1));

        messageJLabel.setText("Message");
        add(messageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 314, -1, -1));
        add(testMessageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 309, 165, -1));

        patientJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient name", "Appoint Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(patientJTable);
        if (patientJTable.getColumnModel().getColumnCount() > 0) {
            patientJTable.getColumnModel().getColumn(0).setResizable(false);
            patientJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 407, 1095, 253));

        messageJLabel1.setText("Message");
        add(messageJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 677, -1, -1));
        add(patientMessageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 672, 172, -1));

        sendResultJButton.setText("Send Result");
        sendResultJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendResultJButtonActionPerformed(evt);
            }
        });
        add(sendResultJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 704, -1, -1));

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1019, 309, 88, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 227, 226));
        jLabel1.setText("Medical Test");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 227, 226));
        jLabel2.setText("My Patient");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 379, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/doctor.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 550, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
        String message = testMessageJTextField.getText();
        
        if(message == null){
            JOptionPane.showMessageDialog(null, "Message Should Not Be Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent");
        request.setRequestDate(new Date());
        
        Organization organization = null;
        for(Organization o : enterprise.getOrganizationCatalog().getOrganizationCatalog()){
            if(o instanceof AssistantOrganization){
                organization = o;
                break;
            }
        }
        if(organization != null){
            organization.getWorkQueue().getWorkRequestCatalog().add(request);
            account.getWorkQueue().getWorkRequestCatalog().add(request);
        }
        populateTestTable();
        testMessageJTextField.setText("");
    }//GEN-LAST:event_requestJButtonActionPerformed

    private void sendResultJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendResultJButtonActionPerformed
        // TODO add your handling code here:
        //SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String message = patientMessageJTextField.getText();
        if(message == null){
            JOptionPane.showMessageDialog(null, "Message Should Not Be Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WorkRequest request = new WorkRequest();
        request.setMessage(message);
        request.setSender(account);
        request.setResolveDate(new Date());
        
        
        int selectedPatient = patientJTable.getSelectedRow();
        if(selectedPatient < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String pname = (String) patientJTable.getValueAt(selectedPatient, 0);
        enterprise.getSelectedPatient(pname).getWorkQueue().getWorkRequestCatalog().add(request);
        populatePatientTable();
        JOptionPane.showMessageDialog(null, "Result Saved!!", "Warning", JOptionPane.WARNING_MESSAGE);
        patientMessageJTextField.setText("");
    }//GEN-LAST:event_sendResultJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = testJTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WorkRequest request = (WorkRequest) testJTable.getValueAt(selectedRow, 2);
        account.getWorkQueue().getWorkRequestCatalog().remove(request);
        populateTestTable();
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel messageJLabel;
    private javax.swing.JLabel messageJLabel1;
    private javax.swing.JTable patientJTable;
    private javax.swing.JTextField patientMessageJTextField;
    private javax.swing.JButton removeJButton;
    private javax.swing.JButton requestJButton;
    private javax.swing.JButton sendResultJButton;
    private javax.swing.JTable testJTable;
    private javax.swing.JTextField testMessageJTextField;
    // End of variables declaration//GEN-END:variables
}
