/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.ConfigureBusiness;
import business.DB4OUtil.DB4OUtil;
import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zack
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setExtendedState(MainJFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        usernameJLabel = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        loginJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        passwordJPasswordField = new javax.swing.JPasswordField();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        controlJPanel.setPreferredSize(new java.awt.Dimension(150, 435));
        controlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameJLabel.setText("Username");
        controlJPanel.add(usernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));
        controlJPanel.add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 150, -1));

        passwordJLabel.setText("Password");
        controlJPanel.add(passwordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 89, -1, -1));

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(loginJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 157, 138, -1));

        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, 138, -1));
        controlJPanel.add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 150, -1));

        jSplitPane1.setLeftComponent(controlJPanel);

        container.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/background.png"))); // NOI18N
        container.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO add your handling code here:
        String username = usernameJTextField.getText().trim();
        char[] passwordCharArray = passwordJPasswordField.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        UserAccount userAccount = system.getUserAccountCatalog().authenticateUser(username, password);
        
        Network inCountry = null;
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        
        if(userAccount == null){
            for(Network network : system.getNetworkCatalog()){
                userAccount = network.getUserAccountCatalog().authenticateUser(username, password);
                if(userAccount != null){
                    inCountry = network;
                    break;
                }
            }
            
        }
        if(userAccount == null){
            for(Network network : system.getNetworkCatalog()){
                for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
                    userAccount = enterprise.getUserAccountCatalog().authenticateUser(username, password);
                    if(userAccount != null){
                        inCountry = network;
                        inEnterprise = enterprise;
                        break;
                    }
                }
                break;
            }
        }
        if(userAccount == null){
            for(Network network : system.getNetworkCatalog()){
                for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
                    for(Organization organization : enterprise.getOrganizationCatalog().getOrganizationCatalog()){
                        userAccount = organization.getUserAccountCatalog().authenticateUser(username, password);  
                        if(userAccount != null){
                            inCountry = network;
                            inEnterprise = enterprise;
                            inOrganization = organization;
                            break;
                        }
                    }
                    if(inEnterprise != null){
                        break;
                    }
                }
                if(inCountry != null){
                    break;
                }
            }
        }
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "Invalid useraccount!");
            return;
        }        
        
        else{
            CardLayout layout = (CardLayout) container.getLayout();
            container.add("workArea",userAccount.getRole().createWorkArea(container, userAccount, inOrganization, inEnterprise, inCountry, system));
            layout.next(container);
        }
        loginJButton.setEnabled(false);
        logoutJButton.setEnabled(true);
        usernameJTextField.setEnabled(false);
        passwordJPasswordField.setEnabled(false);
        
       
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        // TODO add your handling code here:
        logoutJButton.setEnabled(false);
        usernameJTextField.setEnabled(true);
        passwordJPasswordField.setEnabled(true);
        loginJButton.setEnabled(true);
        
        usernameJTextField.setText("");
        passwordJPasswordField.setText("");
        container.removeAll();
        JPanel blankJP = new JPanel();
        container.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.next(container);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
