/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalEnterpriseAdminWorkArea;

import business.enterprise.Enterprise;
import business.enterprise.HospitalEnterprise;
import business.organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author zack
 */
public class EnterpriseSystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseSystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    HospitalEnterprise enterprise;
    public EnterpriseSystemAdminWorkAreaJPanel(JPanel userProcessContainer,HospitalEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTree();
    }

    public void populateTree(){
        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();
        JTree.setRootVisible(false);
        ArrayList<Organization> organizationCatalog = enterprise.getOrganizationCatalog().getOrganizationCatalog();
        
        Organization organization;
        
        DefaultMutableTreeNode root= (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        
        DefaultMutableTreeNode organizationNodes;
        
        for(int i = 0; i < organizationCatalog.size(); i++){
            organization = organizationCatalog.get(i);
            organizationNodes = new DefaultMutableTreeNode(organization.getName());
            root.insert(organizationNodes, i);
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        organizationJLabel = new javax.swing.JLabel();
        manageOrganizationJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageEmployeeUseraccountButton = new javax.swing.JButton();
        manageOrganizationChiefJButton = new javax.swing.JButton();
        manageMedicineStockJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTree1.setMaximumSize(new java.awt.Dimension(100, 76));
        jTree1.setPreferredSize(new java.awt.Dimension(100, 76));
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        JTree.setMaximumSize(new java.awt.Dimension(100, 100));
        JTree.setPreferredSize(new java.awt.Dimension(300, 100));
        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                JTreeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(JTree);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selected Organization:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 35));
        jPanel1.add(organizationJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 0, 134, 35));

        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 238, -1));

        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 111, 238, -1));

        manageEmployeeUseraccountButton.setText("Manage Employee Useraccount");
        manageEmployeeUseraccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeUseraccountButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageEmployeeUseraccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 240, -1));

        manageOrganizationChiefJButton.setText("Manage Organization Chief");
        manageOrganizationChiefJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationChiefJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageOrganizationChiefJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 238, -1));

        manageMedicineStockJButton.setText("Manage Medicine Stock");
        manageMedicineStockJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMedicineStockJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageMedicineStockJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 181, 238, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/hospital.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1280, 190));

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_JTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode=(DefaultMutableTreeNode)JTree.getLastSelectedPathComponent();
        if(selectedNode!=null){
            organizationJLabel.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_JTreeValueChanged

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizationEmployeeJPanel manageOrganizationEmployeeJPanel = new ManageOrganizationEmployeeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationEmployeeJPanel", manageOrganizationEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageEmployeeUseraccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeUseraccountButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizationEmployeeUseraccountJPanel manageOrganizationEmployeeUseraccountJPanel = new ManageOrganizationEmployeeUseraccountJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("manageOrganizationEmployeeUseraccountJPanel", manageOrganizationEmployeeUseraccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeUseraccountButtonActionPerformed

    private void manageOrganizationChiefJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationChiefJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizationChiefJPanel manageOrganizationChiefJPanel = new ManageOrganizationChiefJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("manageOrganizationChiefJPanel", manageOrganizationChiefJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationChiefJButtonActionPerformed

    private void manageMedicineStockJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMedicineStockJButtonActionPerformed
        // TODO add your handling code here:
        ManageMedicineStockJPanel manageMedicineStockJPanel = new ManageMedicineStockJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("manageMedicineStockJPanel", manageMedicineStockJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMedicineStockJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageEmployeeUseraccountButton;
    private javax.swing.JButton manageMedicineStockJButton;
    private javax.swing.JButton manageOrganizationChiefJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JLabel organizationJLabel;
    // End of variables declaration//GEN-END:variables
}
