/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HealthcareEnterpriseAdminWorkArea;

import business.employee.Employee;
import business.enterprise.Enterprise;
import business.enterprise.HealthcareEnterprise;
import business.organization.Organization;
import business.role.AnalystRole;
import business.role.CollectorRole;
import business.role.Role;
import business.role.Role.HealthcareRoleType;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zack
 */
public class ManageOrganizationEmployeeUseraccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationEmployeeUseraccountJPanel
     */
    JPanel userProcessContainer;
    HealthcareEnterprise enterprise;
    
    public ManageOrganizationEmployeeUseraccountJPanel(JPanel userProcessContainer,HealthcareEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
        populateComboBox();
        populateRoleBox();
    }

    public void populateComboBox(){
        organizationNameJComboBox.removeAllItems();
        employeeRoleJComboBox.removeAllItems();
        for(Organization organization : enterprise.getOrganizationCatalog().getOrganizationCatalog()){
            organizationNameJComboBox.addItem(organization);
        }
    }
    
    public void populateRoleBox(){
        employeeRoleJComboBox.removeAllItems();
        if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Healthcare_Community)){
            for(HealthcareRoleType type : Role.HealthcareRoleType.values()){
                if(!type.equals(Role.HealthcareRoleType.HealthcareManager)) employeeRoleJComboBox.addItem(type);
            }
        }
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) JTable.getModel();
        model.setRowCount(0);
        for(Organization organization : enterprise.getOrganizationCatalog().getOrganizationCatalog()){
            for(UserAccount userAccount : organization.getUserAccountCatalog().getUserAccountCatalog()){
                Object[] row = new Object[3];
                row[0] = organization.getName();
                row[1] = userAccount.getEmployee().getName();
                row[2] = userAccount.getRole();
                model.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        organizationNameJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        employeeRoleJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        usernameJLabel = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        submitJButton = new javax.swing.JButton();
        resetJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 46));

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Organization Type", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 510, 138));

        jLabel1.setText("Organization Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        add(organizationNameJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 137, -1));

        jLabel3.setText("Employee Role");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        employeeRoleJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeRoleJComboBoxActionPerformed(evt);
            }
        });
        add(employeeRoleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 137, -1));

        jLabel2.setText("Employee Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 136, -1));

        usernameJLabel.setText("Username");
        add(usernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 136, -1));

        passwordJLabel.setText("Password");
        add(passwordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 136, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        resetJButton.setText("Reset");
        resetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJButtonActionPerformed(evt);
            }
        });
        add(resetJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 88, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EnterpriseSystemAdminWorkAreaJPanel sysAdminwjp = (EnterpriseSystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void employeeRoleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRoleJComboBoxActionPerformed
        // TODO add your handling code here:
        //        Organization organization = (Organization) organizationNameJComboBox.getSelectedItem();
        //        if(organization != null){
            //            populateRoleComboBox(enterprise);
            //        }
    }//GEN-LAST:event_employeeRoleJComboBoxActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) organizationNameJComboBox.getSelectedItem();
        HealthcareRoleType type = (HealthcareRoleType) employeeRoleJComboBox.getSelectedItem();

        String name = nameJTextField.getText().trim();
        String username = usernameJTextField.getText().trim();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        
        if(!name.matches("[a-zA-Z]+")){
            JOptionPane.showMessageDialog(null, "Invalid employee name!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Employee employee = organization.getEmployeeCatalog().createEmployee(name);
        if(type.equals(HealthcareRoleType.Collector)){
            UserAccount account = organization.getUserAccountCatalog().createUserAccount(username, password, employee, new CollectorRole());
        }
        else if(type.equals(HealthcareRoleType.Analyst)){
            UserAccount account = organization.getUserAccountCatalog().createUserAccount(username, password, employee, new AnalystRole());
        }
        else{
            ;
        }
        populateTable();
        nameJTextField.setText("");
        usernameJTextField.setText("");
        passwordJPasswordField.setText("");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void resetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJButtonActionPerformed
        // TODO add your handling code here:
        nameJTextField.setText("");
        usernameJTextField.setText("");
        passwordJPasswordField.setText("");
    }//GEN-LAST:event_resetJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox employeeRoleJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox organizationNameJComboBox;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton resetJButton;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
