/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ResearcherWorkArea;

import business.enterprise.Enterprise;
import business.medicine.Medicine;
import business.organization.DoctorOrganization;
import business.organization.Organization;
import business.organization.ResearcherOrganization;
import business.organization.TesterOrganization;
import business.useraccount.UserAccount;
import business.workqueue.MedicineTestWorkRequest;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zack
 */
public class ResearcherWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResearcherWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    ResearcherOrganization organization;
    Enterprise enterprise;
    public ResearcherWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ResearcherOrganization organization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        requestButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        formulaJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        usesJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Medicine Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 244, -1));

        jLabel2.setText("Medicine Description");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionJTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        requestButton.setText("Request Clinical Test");
        requestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestButtonActionPerformed(evt);
            }
        });
        add(requestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel3.setText("Medicine Formula ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
        add(formulaJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 244, -1));

        jLabel4.setText("Medicine uses");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
        add(usesJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 244, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 81, 86));
        jLabel6.setText("New Medicine Info");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/medicine.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, -1, 190));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/science-1.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestButtonActionPerformed
        // TODO add your handling code here:
        String name = nameJTextField.getText();
        String description = descriptionJTextArea.getText();
        String formula = formulaJTextField.getText();
        String uses = usesJTextField.getText();
        
        if(!name.matches("[a-zA-Z]+")){
            JOptionPane.showMessageDialog(null, "Invalid medicine name!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Medicine medicine = new Medicine(name,description,formula,uses);
        
        if(name == null || description == null){
            JOptionPane.showMessageDialog(null, "Name or Description Should Not Be Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        MedicineTestWorkRequest request = new MedicineTestWorkRequest();
        request.setMedicine(medicine);
        request.setSender(account);
        request.setStatus("Pending");
        request.setRequestDate(new Date());
        
        Organization organization = null;
        for(Organization o : enterprise.getOrganizationCatalog().getOrganizationCatalog()){
            if(o instanceof TesterOrganization){
                organization = o;
                break;
            }
        }
        if(organization != null){
            organization.getWorkQueue().getWorkRequestCatalog().add(request);
        }
        nameJTextField.setText("");
        descriptionJTextArea.setText("");
        formulaJTextField.setText("");
        usesJTextField.setText("");
        JOptionPane.showMessageDialog(null, "Request has Sent!!", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_requestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JTextField formulaJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton requestButton;
    private javax.swing.JTextField usesJTextField;
    // End of variables declaration//GEN-END:variables
}
