/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.MedicineEnterpriseAdminWorkArea;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.Organization.MedicineOrganizationType;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zack
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    public ManageOrganizationJPanel(JPanel userProcessContainer,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        populateTable();
        populateComboBox();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) JTable.getModel();
        model.setRowCount(0);
        for(Organization organization : enterprise.getOrganizationCatalog().getOrganizationCatalog()){
            Object[] row = new Object[2];
            row[0] = organization.getName();
            row[1] = organization.getMedicineOrganizationType();
            //row[2] = organization.getOrganizationChief();
            model.addRow(row);
        }
    }
    
    public void populateComboBox(){
        //organizationChiefJComboBox.removeAllItems();
        organizationTypeJComboBox.removeAllItems();
        for(MedicineOrganizationType type : Organization.MedicineOrganizationType.values()){
            if(!type.equals(MedicineOrganizationType.Manager))
            organizationTypeJComboBox.addItem(type);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        removeJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        organizationNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        organizationTypeJComboBox = new javax.swing.JComboBox();
        addOrganizationJButton = new javax.swing.JButton();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Organization Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 141));

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 88, -1));

        jLabel1.setText("Organiztion Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));
        jPanel1.add(organizationNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 122, -1));

        jLabel2.setText("Organization Type");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        organizationTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationTypeJComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(organizationTypeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 121, -1));

        addOrganizationJButton.setText("Add Organization");
        addOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backJButton)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EnterpriseSystemAdminWorkAreaJPanel sysAdminwjp = (EnterpriseSystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String organizationName = (String) JTable.getValueAt(selectedRow, 0);
        Organization o = null;
        for(Organization organization : enterprise.getOrganizationCatalog().getOrganizationCatalog()){
            if(organization.getName().equals(organizationName)){
                o = organization;
                break;
            }
        }
        enterprise.getOrganizationCatalog().getOrganizationCatalog().remove(o);
        populateTable();
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void organizationTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationTypeJComboBoxActionPerformed
        // TODO add your handling code here:
        MedicineOrganizationType type = (MedicineOrganizationType) organizationTypeJComboBox.getSelectedItem();
        //populateChiefComboBox(type);
    }//GEN-LAST:event_organizationTypeJComboBoxActionPerformed

    private void addOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationJButtonActionPerformed
        String name = organizationNameJTextField.getText().trim();
        MedicineOrganizationType type = (MedicineOrganizationType) organizationTypeJComboBox.getSelectedItem();
        //String chief = organizationChiefJComboBox.getSelectedItem().toString();
        enterprise.getOrganizationCatalog().addOrganization(name,type);
        populateTable();
        organizationNameJTextField.setText("");
    }//GEN-LAST:event_addOrganizationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton addOrganizationJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField organizationNameJTextField;
    private javax.swing.JComboBox organizationTypeJComboBox;
    private javax.swing.JButton removeJButton;
    // End of variables declaration//GEN-END:variables
}
