/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import business.EcoSystem;
import business.employee.Employee;
import business.network.Network;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zack
 */
public class ManageCountryEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCountryEmployeeJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    
    public ManageCountryEmployeeJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTable();
        //populateComboBox();
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        model.setRowCount(0);
        for(Network network : system.getNetworkCatalog()){
            for(Employee employee : network.getEmployeeCatalog().getEmployeeCatalog()){
                Object[] row = new Object[2];
                row[0] = network.getCountryName();
                row[1] = employee.getName();
                model.addRow(row);
            }
        }
    }
    
//    private void populateComboBox(){
//        countryJComboBox.removeAllItems();
//        for(Network network : system.getNetworkCatalog()){
//            countryJComboBox.addItem(network);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        birthdayJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phonenumberJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        genderJComboBox = new javax.swing.JComboBox();
        removeJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Country", "Employee Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setResizable(false);
            employeeTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 184, -1, 154));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 120, -1, 46));

        jLabel1.setText("Gender");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 388, -1, -1));

        jLabel2.setText("Birthday");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 389, -1, -1));
        add(birthdayJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 384, 113, -1));

        jLabel3.setText("Phonenumber");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 417, -1, -1));
        add(phonenumberJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 412, 98, -1));

        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 417, -1, -1));
        add(emailJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 412, 113, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 444, -1, -1));

        genderJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "male", "female" }));
        add(genderJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 384, 100, -1));

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = employeeTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String name = (String) employeeTable.getValueAt(selectedRow, 1);
        String gender =  (String) genderJComboBox.getSelectedItem();
        String birthday = birthdayJTextField.getText();
        String phonenumber = phonenumberJTextField.getText();
        String email = emailJTextField.getText();
        
        if(phonenumber.length() != 10){
            JOptionPane.showMessageDialog(null, "Invalid phone number!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!email.contains("@")){
            JOptionPane.showMessageDialog(null, "Invalid email!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for(Network network : system.getNetworkCatalog()){
            for(Employee employee : network.getEmployeeCatalog().getEmployeeCatalog()){
                if(employee.getName().equals(name)){
                    employee.setGender(gender);
                    employee.setBirthday(birthday);
                    employee.setPhonenumber(phonenumber);
                    employee.setEmail(email);
                    JOptionPane.showMessageDialog(null, "Change Saved!!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        birthdayJTextField.setText("");
        phonenumberJTextField.setText("");
        emailJTextField.setText("");
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = employeeTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String employeeName = (String) employeeTable.getValueAt(selectedRow, 1);
        String countryName = (String) employeeTable.getValueAt(selectedRow, 0);
        UserAccount ua = null;
        for(Network network : system.getNetworkCatalog()){
            if(network.getCountryName().equals(countryName)){
                for(UserAccount useraccount : network.getUserAccountCatalog().getUserAccountCatalog()){
                    if(useraccount.getEmployee().getName().equals(employeeName)){
                       ua = useraccount;
                       break;
                    }
                }
            }
            if(ua != null){
                break;
            }
        }
        
        for(Network network : system.getNetworkCatalog()){
            if(network.getCountryName().equals(countryName)){
                network.getEmployeeCatalog().getEmployeeCatalog().remove(ua.getEmployee());
                network.getUserAccountCatalog().getUserAccountCatalog().remove(ua);
                break;
            }
        }
        populateTable();
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField birthdayJTextField;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JTable employeeTable;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phonenumberJTextField;
    private javax.swing.JButton removeJButton;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
