/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author zack
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.system=system;
        populateTree();
    }

    public void populateTree(){
        DefaultTreeModel model = (DefaultTreeModel) systemJTree.getModel();
        systemJTree.setRootVisible(false);
        ArrayList<Network> networkCatalog = system.getNetworkCatalog();
        ArrayList<Enterprise> enterpriseCatalog;
        ArrayList<Organization> organizationCatalog;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        //DefaultMutableTreeNode networks=new DefaultMutableTreeNode();
        DefaultMutableTreeNode root= (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        //root.insert(networks,0);
        
        DefaultMutableTreeNode networkNodes;
        DefaultMutableTreeNode enterpriseNodes;
        DefaultMutableTreeNode organizationNodes;
        
        for(int i = 0; i < networkCatalog.size(); i++){
            network = networkCatalog.get(i);
            networkNodes=new DefaultMutableTreeNode(network.getName());
            root.insert(networkNodes, i);
            
            enterpriseCatalog = network.getEnterpriseCatalog().getEnterpriseCatalog();
            
            for(int j = 0; j < enterpriseCatalog.size(); j++){
                enterprise = enterpriseCatalog.get(j);
                enterpriseNodes=new DefaultMutableTreeNode(enterprise.getName());
                networkNodes.insert(enterpriseNodes,j);
                
                organizationCatalog = enterprise.getOrganizationCatalog().getOrganizationCatalog();
                
                for(int k = 0; k < organizationCatalog.size(); k++){
                    organization = organizationCatalog.get(k);
                    organizationNodes=new DefaultMutableTreeNode(organization.getName());
                    enterpriseNodes.insert(organizationNodes, k);
                }
            }
            
        }
        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        systemJTree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        manageCountryJButton = new javax.swing.JButton();
        manageCountryEmployeeJButton = new javax.swing.JButton();
        manageCountryAdminJButton = new javax.swing.JButton();
        JLabel = new javax.swing.JLabel();
        countryJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        countryNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        systemJTree.setPreferredSize(new java.awt.Dimension(300, 76));
        systemJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                systemJTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(systemJTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 506));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageCountryJButton.setText("Manage Country");
        manageCountryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCountryJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageCountryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 273, -1));

        manageCountryEmployeeJButton.setText("Manage Country Admin Employee");
        manageCountryEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCountryEmployeeJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageCountryEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 273, -1));

        manageCountryAdminJButton.setText("Manage Country Admin Useraccount");
        manageCountryAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCountryAdminJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageCountryAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, -1));

        JLabel.setText("Selected Item:");
        jPanel1.add(JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 124, 35));
        jPanel1.add(countryJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 41, 158, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 0, -1, -1));
        jPanel1.add(countryNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/maxresdefault.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1250, 1160));

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1286, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageCountryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCountryJButtonActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCountryJButtonActionPerformed

    private void manageCountryEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCountryEmployeeJButtonActionPerformed
        // TODO add your handling code here:
        ManageCountryEmployeeJPanel manageNetworkJPanel=new ManageCountryEmployeeJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCountryEmployeeJButtonActionPerformed

    private void manageCountryAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCountryAdminJButtonActionPerformed
        // TODO add your handling code here:
        ManageCountryAdminJPanel manageNetworkJPanel=new ManageCountryAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCountryAdminJButtonActionPerformed

    private void systemJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_systemJTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode=(DefaultMutableTreeNode)systemJTree.getLastSelectedPathComponent();
        if(selectedNode!=null){
            countryNameLabel.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_systemJTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JLabel countryJLabel;
    private javax.swing.JLabel countryNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageCountryAdminJButton;
    private javax.swing.JButton manageCountryEmployeeJButton;
    private javax.swing.JButton manageCountryJButton;
    private javax.swing.JTree systemJTree;
    // End of variables declaration//GEN-END:variables
}
