/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AnalystWorkArea;

import business.disease.DiseaseSample;
import business.enterprise.Enterprise;
import business.enterprise.HealthcareEnterprise;
import business.organization.AnalystOrganization;
import business.useraccount.UserAccount;
import java.awt.GridLayout;
import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zack
 */
public class AnalystWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalystWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    AnalystOrganization organization;
    HealthcareEnterprise enterprise;
    public AnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, AnalystOrganization organization,HealthcareEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        populateTable();
        populateAxisComboBox();
        populatePieComboBox();
        populateLineComboBox();
        populateCompareComboBox();
    }

    public void populateCompareComboBox(){
        compareJComboBox1.removeAllItems();
        compareJComboBox2.removeAllItems();
        statisticsJComboBox.removeAllItems();
        HashSet set = new HashSet();
        for(DiseaseSample sample : enterprise.getSampleCatalog()){
            set.add(sample.getCountryCode());
        }
        Iterator<String> p = set.iterator();
        while(p.hasNext()){
            String name = p.next();
            compareJComboBox1.addItem(name);
            compareJComboBox2.addItem(name);
            statisticsJComboBox.addItem(name);
        }
    }
    
    public void populateLineComboBox(){
        lineComboBox.removeAllItems();
        lineComboBox.addItem("Reference Date");
    }
    
    public void populatePieComboBox(){
        pieComboBox.removeAllItems();
        pieComboBox.addItem("CountryCode");
        pieComboBox.addItem("Sex");
        pieComboBox.addItem("Age");
        pieComboBox.addItem("Reference Date");
        
    }
    
    public void populateAxisComboBox(){
        xaxisJComboBox.removeAllItems();
        xaxisJComboBox.addItem("CountryCode");
        //xaxisJComboBox.addItem("GeographicArea");
        xaxisJComboBox.addItem("Sex");
        xaxisJComboBox.addItem("Age");
        xaxisJComboBox.addItem("VirusType");
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) JTable.getModel();
        model.setRowCount(0);
        for(DiseaseSample sample : enterprise.getSampleCatalog()){
            Object[] row = new Object[15];
            row[0] = sample.getSequence();
            row[1] = sample.getCountryCode();
            row[2] = sample.getGeographicArea();
            row[3] = sample.getReferenceDate();
            row[4] = sample.getSex();
            row[5] = sample.getAge();
            row[6] = sample.getComments();
            row[7] = sample.getDataType();
            row[8] = sample.getInfo();
            row[9] = sample.getVirusType();
            row[10] = sample.getNocase();
            row[11] = sample.getNodeath();
            row[12] = sample.getPrev_rate();
            row[13] = sample.getInc_rate();
            row[14] = sample.getSpecimenType();
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        xaxisJComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Parameter = new javax.swing.JLabel();
        pieComboBox = new javax.swing.JComboBox<>();
        generatePieChartJButton = new javax.swing.JButton();
        generateLineChartJButton = new javax.swing.JButton();
        Parameter1 = new javax.swing.JLabel();
        lineComboBox = new javax.swing.JComboBox<>();
        compareJComboBox2 = new javax.swing.JComboBox();
        compareJComboBox1 = new javax.swing.JComboBox();
        compareJButton = new javax.swing.JButton();
        statisticsJComboBox = new javax.swing.JComboBox();
        viewStatisticJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sequence", "Country Code", "Geographic Area", "Reference Date", "Sex", "Age", "Comments", "Data Type", "info", "Virus Type", "No Case", "No Death", "Prev Rate", "Inc Rate", "Specimen Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);
        if (JTable.getColumnModel().getColumnCount() > 0) {
            JTable.getColumnModel().getColumn(0).setResizable(false);
            JTable.getColumnModel().getColumn(1).setResizable(false);
            JTable.getColumnModel().getColumn(2).setResizable(false);
            JTable.getColumnModel().getColumn(3).setResizable(false);
            JTable.getColumnModel().getColumn(4).setResizable(false);
            JTable.getColumnModel().getColumn(5).setResizable(false);
            JTable.getColumnModel().getColumn(6).setResizable(false);
            JTable.getColumnModel().getColumn(7).setResizable(false);
            JTable.getColumnModel().getColumn(8).setResizable(false);
            JTable.getColumnModel().getColumn(9).setResizable(false);
            JTable.getColumnModel().getColumn(10).setResizable(false);
            JTable.getColumnModel().getColumn(11).setResizable(false);
            JTable.getColumnModel().getColumn(12).setResizable(false);
            JTable.getColumnModel().getColumn(13).setResizable(false);
            JTable.getColumnModel().getColumn(14).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, 1460, -1));

        xaxisJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(xaxisJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 493, 122, -1));

        jLabel1.setText("Parameter");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 497, -1, -1));

        jButton1.setText("Generate Bar Chart ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 526, 170, -1));

        Parameter.setText("Parameter");
        add(Parameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 565, -1, -1));

        pieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(pieComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 561, 128, -1));

        generatePieChartJButton.setText("Generate Pie Chart");
        generatePieChartJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePieChartJButtonActionPerformed(evt);
            }
        });
        add(generatePieChartJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 594, 165, -1));

        generateLineChartJButton.setText("Generate Line Chart");
        generateLineChartJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateLineChartJButtonActionPerformed(evt);
            }
        });
        add(generateLineChartJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 674, 177, -1));

        Parameter1.setText("Parameter");
        add(Parameter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 645, -1, -1));

        lineComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(lineComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 641, 128, -1));

        compareJComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(compareJComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 551, 196, -1));

        compareJComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(compareJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 493, 196, -1));

        compareJButton.setText("Compare");
        compareJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareJButtonActionPerformed(evt);
            }
        });
        add(compareJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 594, -1, -1));

        statisticsJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(statisticsJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 496, 208, -1));

        viewStatisticJButton.setText("View ");
        viewStatisticJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatisticJButtonActionPerformed(evt);
            }
        });
        add(viewStatisticJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 535, 100, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 78, 101));
        jLabel2.setText("Data Analysis");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 78, 101));
        jLabel3.setText("Overall Statistics");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 471, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(46, 78, 101));
        jLabel4.setText("Compare Two Countries");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 471, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 78, 101));
        jLabel5.setText("One Country Details");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 467, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/healthcare.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Data-analytics-99760451.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, -120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame(xaxisJComboBox.getSelectedItem().toString() + "Bar Chart");
	//frame.setLayout(new GridLayout(2,2,10,10));
	frame.add(new DiseaseBarChart(xaxisJComboBox.getSelectedItem().toString(),enterprise.getSampleCatalog()).getChartPanel());
        frame.setBounds(50, 50, 1500, 1500);
	frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generatePieChartJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePieChartJButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame(pieComboBox.getSelectedItem().toString() + "Pie Chart");
	//frame.setLayout(new GridLayout(2,2,10,10));
	frame.add(new DiseasePieChart(pieComboBox.getSelectedItem().toString(),enterprise.getSampleCatalog()).getChartPanel());
        frame.setBounds(50, 50, 1500, 1500);
	frame.setVisible(true);
    }//GEN-LAST:event_generatePieChartJButtonActionPerformed

    private void generateLineChartJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateLineChartJButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame(lineComboBox.getSelectedItem().toString() + "line Chart");
	//frame.setLayout(new GridLayout(2,2,10,10));
	frame.add(new DiseaseLineChart(lineComboBox.getSelectedItem().toString(),enterprise.getSampleCatalog()).getChartPanel());
        frame.setBounds(50, 50, 1500, 1500);
	frame.setVisible(true);
    }//GEN-LAST:event_generateLineChartJButtonActionPerformed

    private void compareJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareJButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame(compareJComboBox1.getSelectedItem().toString() + " vs "+ compareJComboBox2.getSelectedItem().toString());
        frame.setLayout(new GridLayout(2,2,10,10));
        frame.add(new DiseaseBarChart(compareJComboBox1.getSelectedItem().toString(),compareJComboBox2.getSelectedItem().toString() ,enterprise.getSampleCatalog()).getChartPanel());
        frame.add(new DiseasePieChart(compareJComboBox1.getSelectedItem().toString(),compareJComboBox2.getSelectedItem().toString() ,enterprise.getSampleCatalog()).getChartPanel());
        //frame.add(new DiseaseLineChart(compareJComboBox1.getSelectedItem().toString(),compareJComboBox2.getSelectedItem().toString() ,enterprise.getSampleCatalog()).getChartPanel());
        frame.setBounds(50, 50, 1500,1500);
	frame.setVisible(true);
    }//GEN-LAST:event_compareJButtonActionPerformed

    private void viewStatisticJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatisticJButtonActionPerformed
        // TODO add your handling code here:
        JFrame frame=new JFrame(statisticsJComboBox.getSelectedItem().toString()+" Overall Statistics");
        frame.setLayout(new GridLayout(2,2,10,10));
        frame.add(new DiseaseBarChart(statisticsJComboBox.getSelectedItem().toString(),enterprise.getSampleCatalog(),"one").getChartPanel());
        frame.add(new DiseasePieChart(statisticsJComboBox.getSelectedItem().toString(),enterprise.getSampleCatalog(),"one").getChartPanel());
        frame.add(new DiseaseLineChart(statisticsJComboBox.getSelectedItem().toString(),enterprise.getSampleCatalog(),"one").getChartPanel());
        frame.add(new StatisticChart(statisticsJComboBox.getSelectedItem().toString(),enterprise.getSampleCatalog()).getChartPanel());
        frame.setBounds(50, 50, 1500,1500);
	frame.setVisible(true);
    }//GEN-LAST:event_viewStatisticJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JLabel Parameter;
    private javax.swing.JLabel Parameter1;
    private javax.swing.JButton compareJButton;
    private javax.swing.JComboBox compareJComboBox1;
    private javax.swing.JComboBox compareJComboBox2;
    private javax.swing.JButton generateLineChartJButton;
    private javax.swing.JButton generatePieChartJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lineComboBox;
    private javax.swing.JComboBox<String> pieComboBox;
    private javax.swing.JComboBox statisticsJComboBox;
    private javax.swing.JButton viewStatisticJButton;
    private javax.swing.JComboBox<String> xaxisJComboBox;
    // End of variables declaration//GEN-END:variables
}
