/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryAdminWorkArea;

import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import userinterface.SystemAdminWorkArea.ManageCountryAdminJPanel;
import userinterface.SystemAdminWorkArea.ManageCountryEmployeeJPanel;

/**
 *
 * @author zack
 */
public class CountrySystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CountrySystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Network network;
    public CountrySystemAdminWorkAreaJPanel(JPanel userProcessContainer,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel model = (DefaultTreeModel) JTree.getModel();
        JTree.setRootVisible(false);
        ArrayList<Enterprise> enterpriseCatalog = network.getEnterpriseCatalog().getEnterpriseCatalog();
        ArrayList<Organization> organizationCatalog;
        
        Enterprise enterprise;
        Organization organization;
        
        //DefaultMutableTreeNode enterprises = new DefaultMutableTreeNode();
        DefaultMutableTreeNode root= (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        //root.insert(enterprises, 0);
        
        DefaultMutableTreeNode enterpriseNodes;
        DefaultMutableTreeNode organizationNodes;
        
        for(int i = 0; i < enterpriseCatalog.size(); i++){
            enterprise = enterpriseCatalog.get(i);
            enterpriseNodes = new DefaultMutableTreeNode(enterprise.getName());
            root.insert(enterpriseNodes, i);
            
            organizationCatalog = enterprise.getOrganizationCatalog().getOrganizationCatalog();
            for(int j = 0; j < organizationCatalog.size(); j++){
                organization = organizationCatalog.get(j);
                organizationNodes=new DefaultMutableTreeNode(organization.getName());
                enterpriseNodes.insert(organizationNodes, j);
            }
        }
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enterpriseJLabel = new javax.swing.JLabel();
        manageEnterpriseJButton = new javax.swing.JButton();
        manageEnterpriseAdminEmployeeJButton = new javax.swing.JButton();
        manageEnterpriseAdminUseraccountJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        JTree.setMaximumSize(new java.awt.Dimension(300, 100));
        JTree.setPreferredSize(new java.awt.Dimension(500, 100));
        JTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                JTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel3.setPreferredSize(new java.awt.Dimension(1500, 954));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selected Enterprise:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 134, 35));
        jPanel3.add(enterpriseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 134, 35));

        manageEnterpriseJButton.setText("Manage Enterrpise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });
        jPanel3.add(manageEnterpriseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 286, -1));

        manageEnterpriseAdminEmployeeJButton.setText("Manage Enterprise Admin Employee");
        manageEnterpriseAdminEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminEmployeeJButtonActionPerformed(evt);
            }
        });
        jPanel3.add(manageEnterpriseAdminEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 286, -1));

        manageEnterpriseAdminUseraccountJButton.setText("Manage Enterprise Admin Useraccount");
        manageEnterpriseAdminUseraccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminUseraccountJButtonActionPerformed(evt);
            }
        });
        jPanel3.add(manageEnterpriseAdminUseraccountJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 280, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/medicine.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1500, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/hospital.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1500, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/healthcare.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1500, -1));

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1708, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_JTreeValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode selectedNode=(DefaultMutableTreeNode)JTree.getLastSelectedPathComponent();
        if(selectedNode!=null){
            enterpriseJLabel.setText(selectedNode.toString());
        }
    }//GEN-LAST:event_JTreeValueChanged

    private void manageEnterpriseAdminUseraccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminUseraccountJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminUseraccountJPanel manageEnterpriseAdminUseraccountJPanel = new ManageEnterpriseAdminUseraccountJPanel(userProcessContainer, network);
        userProcessContainer.add("manageEnterpriseAdminUseraccountJPanel",manageEnterpriseAdminUseraccountJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminUseraccountJButtonActionPerformed

    private void manageEnterpriseAdminEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminEmployeeJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminEmployeeJPanel manageEnterpriseAdminEmployeeJPanel=new ManageEnterpriseAdminEmployeeJPanel(userProcessContainer, network);
        userProcessContainer.add("manageEnterpriseAdminEmployeeJPanel",manageEnterpriseAdminEmployeeJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminEmployeeJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer,network);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTree;
    private javax.swing.JLabel enterpriseJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageEnterpriseAdminEmployeeJButton;
    private javax.swing.JButton manageEnterpriseAdminUseraccountJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    // End of variables declaration//GEN-END:variables
}
