/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryAdminWorkArea;

import business.employee.Employee;
import business.enterprise.Enterprise;
import business.network.Network;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zack
 */
public class ManageEnterpriseAdminEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminEmployeeJPanel
     */
    JPanel userProcessContainer;
    Network network;
    public ManageEnterpriseAdminEmployeeJPanel(JPanel userProcessContainer,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) JTable.getModel();
        model.setRowCount(0);
        for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
            for(Employee employee : enterprise.getEmployeeCatalog().getEmployeeCatalog()){
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = enterprise.getEnterpriseType();
                row[2] = employee.getName();
                model.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        genderJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        birthdayJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phonenumberJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Employee Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);
        if (JTable.getColumnModel().getColumnCount() > 0) {
            JTable.getColumnModel().getColumn(0).setResizable(false);
            JTable.getColumnModel().getColumn(1).setResizable(false);
            JTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setText("Gender");

        genderJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "male", "female" }));

        jLabel2.setText("Birthday");

        jLabel3.setText("Phonenumber");

        jLabel4.setText("Email");

        emailJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJTextFieldActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(backJButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(820, 820, 820)
                .addComponent(removeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(submitJButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(birthdayJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(removeJButton)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(genderJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthdayJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phonenumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(submitJButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CountrySystemAdminWorkAreaJPanel sysAdminwjp = (CountrySystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String name = (String) JTable.getValueAt(selectedRow, 2);
        String gender =  (String) genderJComboBox.getSelectedItem();
        String birthday = birthdayJTextField.getText();
        String phonenumber = phonenumberJTextField.getText();
        String email = emailJTextField.getText();
        if(phonenumber.length() != 10){
            JOptionPane.showMessageDialog(null, "Invalid phone number!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!email.contains("@")){
            JOptionPane.showMessageDialog(null, "Invalid email!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
            for(Employee employee : enterprise.getEmployeeCatalog().getEmployeeCatalog()){
                if(employee.getName().equals(name)){
                    employee.setGender(gender);
                    employee.setBirthday(birthday);
                    employee.setPhonenumber(phonenumber);
                    employee.setEmail(email);
                    JOptionPane.showMessageDialog(null, "Change Saved!!", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        birthdayJTextField.setText("");
        phonenumberJTextField.setText("");
        emailJTextField.setText("");

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void emailJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJTextFieldActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String enterpriseName = (String) JTable.getValueAt(selectedRow, 0);
        String employeeName = (String) JTable.getValueAt(selectedRow, 2);
        UserAccount ua = null;
        for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
            if(enterprise.getName().equals(enterpriseName)){
                for(UserAccount useraccount : enterprise.getUserAccountCatalog().getUserAccountCatalog()){
                    if(useraccount.getEmployee().getName().equals(employeeName)){
                        ua = useraccount;
                        break;
                    }
                }
            }
            if(ua != null){
                break;
            }
        }
        for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
            if(enterprise.getName().equals(enterpriseName)){
                enterprise.getEmployeeCatalog().getEmployeeCatalog().remove(ua.getEmployee());
                enterprise.getUserAccountCatalog().getUserAccountCatalog().remove(ua);
                break;
            }
        }
        populateTable();
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField birthdayJTextField;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JComboBox genderJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phonenumberJTextField;
    private javax.swing.JButton removeJButton;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
