/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryAdminWorkArea;

import business.employee.Employee;
import business.enterprise.Enterprise;
import business.network.Network;
import business.role.HealthcareEnterpriseSystemAdminRole;
import business.role.HospitalEnterpriseSystemAdminRole;
import business.role.MedicineEnterpriseSystemAdminRole;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author zack
 */
public class ManageEnterpriseAdminUseraccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminUseraccountJPanel
     */
    JPanel userProcessContainer;
    Network network;
    public ManageEnterpriseAdminUseraccountJPanel(JPanel userProcessContainer,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        populateTable();
        populateComboBox();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) JTable.getModel();
        model.setRowCount(0);
        for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
            for(UserAccount userAccount : enterprise.getUserAccountCatalog().getUserAccountCatalog()){
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = enterprise.getEnterpriseType();
                row[2] = userAccount.getUsername();
                model.addRow(row);
            }
        }
    }
    
    public void populateComboBox(){
        enterpriseNameJComboBox.removeAllItems();
        for(Enterprise enterprise : network.getEnterpriseCatalog().getEnterpriseCatalog()){
            enterpriseNameJComboBox.addItem(enterprise);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        enterpriseNameJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        usernameJLabel = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        passwordJPasswordField = new javax.swing.JPasswordField();
        submitJButton = new javax.swing.JButton();
        resetJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 46));

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);
        if (JTable.getColumnModel().getColumnCount() > 0) {
            JTable.getColumnModel().getColumn(0).setResizable(false);
            JTable.getColumnModel().getColumn(1).setResizable(false);
            JTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 480, 210));

        jLabel1.setText("Enterprise Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        add(enterpriseNameJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 136, -1));

        jLabel2.setText("Employee Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 136, -1));

        usernameJLabel.setText("Username");
        add(usernameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 136, -1));

        passwordJLabel.setText("Password");
        add(passwordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, -1));
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 136, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, -1, -1));

        resetJButton.setText("Reset");
        resetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJButtonActionPerformed(evt);
            }
        });
        add(resetJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 88, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CountrySystemAdminWorkAreaJPanel sysAdminwjp = (CountrySystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) enterpriseNameJComboBox.getSelectedItem();

        String name = nameJTextField.getText().trim();
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        if(!name.matches("[a-zA-Z]+")){
            JOptionPane.showMessageDialog(null, "Invalid employee name!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Employee employee = enterprise.getEmployeeCatalog().createEmployee(name);
        
        if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)){
            UserAccount account = enterprise.getUserAccountCatalog().createUserAccount(username, password, employee, new HospitalEnterpriseSystemAdminRole());
        }
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Medicine_Company)){
            UserAccount account = enterprise.getUserAccountCatalog().createUserAccount(username, password, employee, new MedicineEnterpriseSystemAdminRole());
        }
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Healthcare_Community)){
            UserAccount account = enterprise.getUserAccountCatalog().createUserAccount(username, password, employee, new HealthcareEnterpriseSystemAdminRole());
        }
        populateTable();
        nameJTextField.setText("");
        usernameJTextField.setText("");
        passwordJPasswordField.setText("");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void resetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJButtonActionPerformed
        // TODO add your handling code here:
        usernameJTextField.setText("");
        passwordJPasswordField.setText("");
    }//GEN-LAST:event_resetJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox enterpriseNameJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton resetJButton;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
