/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TesterWorkArea;

import business.enterprise.Enterprise;
import business.organization.DoctorOrganization;
import business.organization.TesterOrganization;
import business.useraccount.UserAccount;
import business.workqueue.MedicineTestWorkRequest;
import business.workqueue.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zack
 */
public class TesterWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TesterWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    TesterOrganization organization;
    Enterprise enterprise;
    SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    public TesterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, TesterOrganization organization,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        populateTestTable();
    }

    public void populateTestTable(){
        DefaultTableModel model = (DefaultTableModel)testJTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request : organization.getWorkQueue().getWorkRequestCatalog()){
            Object[] row = new Object[9];
            row[0] = format.format(request.getRequestDate());
            if(request.getResolveDate() == null){
                row[1] = null;
            }
            else{
                row[1] = format.format(request.getResolveDate());
            }
            row[2] = request.getSender().getEmployee().getName();
            row[3] = ((MedicineTestWorkRequest) request).getMedicine().getId();
            row[4] = ((MedicineTestWorkRequest) request);
            row[5] = ((MedicineTestWorkRequest) request).getMedicine().getDescription();
            row[6] = request.getStatus();
            row[7] = ((MedicineTestWorkRequest) request).getResult();
            row[8] = ((MedicineTestWorkRequest) request).getComment();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        testJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        submitresultJButton = new javax.swing.JButton();
        testSignJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestDate", "Resolve Date", "Sender", "Medicine ID", "Medicine Name", "Medicine Description", "Status", "Test Sign", "Clinical Test Comment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(testJTable);
        if (testJTable.getColumnModel().getColumnCount() > 0) {
            testJTable.getColumnModel().getColumn(0).setResizable(false);
            testJTable.getColumnModel().getColumn(1).setResizable(false);
            testJTable.getColumnModel().getColumn(2).setResizable(false);
            testJTable.getColumnModel().getColumn(3).setResizable(false);
            testJTable.getColumnModel().getColumn(4).setResizable(false);
            testJTable.getColumnModel().getColumn(5).setResizable(false);
            testJTable.getColumnModel().getColumn(6).setResizable(false);
            testJTable.getColumnModel().getColumn(7).setResizable(false);
            testJTable.getColumnModel().getColumn(8).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1230, 212));

        jLabel1.setText("Test Comment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        resultJTextField.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                resultJTextFieldAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(resultJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 154, -1));

        submitresultJButton.setText("Submit Result");
        submitresultJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitresultJButtonActionPerformed(evt);
            }
        });
        add(submitresultJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 141, -1));

        testSignJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Safe", "Unsafe", "Need More Test" }));
        add(testSignJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel2.setText("Test Sign");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/chemistry.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -10, 530, 580));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 81, 86));
        jLabel5.setText("Clinical Test Result");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/pipette.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/medicine.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, -1, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void submitresultJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitresultJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = testJTable.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        MedicineTestWorkRequest request = (MedicineTestWorkRequest) testJTable.getValueAt(selectedRow, 4);
        request.setResult((String) testSignJComboBox.getSelectedItem());
        request.setComment(resultJTextField.getText());
        request.setStatus("Complete");
        request.setResolveDate(new Date());
        resultJTextField.setText("");
        populateTestTable();
    }//GEN-LAST:event_submitresultJButtonActionPerformed

    private void resultJTextFieldAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_resultJTextFieldAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_resultJTextFieldAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitresultJButton;
    private javax.swing.JTable testJTable;
    private javax.swing.JComboBox testSignJComboBox;
    // End of variables declaration//GEN-END:variables
}
